### ISSUE TITLE
Possible memory leak when vol-metrics-opt-in is enabled

### ISSUE THREAD

**Issue by adriananeci** [kubernetes-sigs/aws-efs-csi-driver#1104]
/kind bug

**What happened?**

I've noticed huge memory usage, over 50G, while enabling the `--vol-metrics-opt-in=true` flag.

![image](https://github.com/kubernetes-sigs/aws-efs-csi-driver/assets/23321264/fd2a819d-02bd-4af0-b09b-59181e0172e0)

Once I've disabled the volume metrics(`--vol-metrics-opt-in=false`) memory utilisation was drastically reduced (under 200M)

![image](https://github.com/kubernetes-sigs/aws-efs-csi-driver/assets/23321264/eb707c18-b692-46c9-a837-db013a2119c2)

**What you expected to happen?**

Memory should remain approximately constant during the pod lifetime.

**How to reproduce it (as minimally and precisely as possible)?**

Enable `--vol-metrics-opt-in=true` and start deploying some bare PVs or PVCs using a storage class.

**Anything else we need to know?**:

Noticed many warnings logs like:
```
W0817 13:26:54.643920       1 vol_statter.go:67] Volume metrics computation is underway for Vol ID: fs-xxx.efs.us-east-1.amazonaws.com and metrics are not available yet.
W0817 13:26:54.644691       1 vol_statter.go:67] Volume metrics computation is underway for Vol ID: fs-bbb.efs.us-east-1.amazonaws.com and metrics are not available yet.
W0817 13:26:54.645385       1 vol_statter.go:67] Volume metrics computation is underway for Vol ID: fs-ccc.efs.us-east-1.amazonaws.com and metrics are not available yet.
W0817 13:26:54.646111       1 vol_statter.go:67] Volume metrics computation is underway for Vol ID: fs-aaa.efs.us-east-1.amazonaws.com and metrics are not available yet.
```

**Environment**
- Kubernetes version (use `kubectl version`):
```
❯ kubectl version
Client Version: v1.28.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.25.12-eks-2d98532
```
- Driver version:
`v1.5.9`

**Please also attach debug logs to help us better diagnose**

- Instructions to gather debug logs can be found [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting)

**Comment by RyanStan** [comment]
Thanks for bringing this to our attention. 

[Here, in our implementation of the NodeGetVolumeStats interface](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/pkg/driver/vol_statter.go#L123), we call this `DiskUsage` function which is defined [here, in the Kubernetes `fs` package](https://github.com/kubernetes/kubernetes/blob/ee265c92fec40cd69d1de010b477717e4c142492/pkg/volume/util/fs/fs.go#L66).

This function walks the file tree and calls stat on each entry. This function will end up consuming an amount of memory that is proportional to the size of your filesystem. 

We've seen similar issues come up for EFS users who run `du` against large filesystems, and notice that `du` consumes a large amount of memory, because it does not spill anything to disk while it iterates over the filesystem and performs its accounting.

We recommend to disable the `--vol-metrics-opt-in` option on large filesystems to avoid consuming too much memory. We will update our documentation to reflect this.
