### ISSUE TITLE
Integration with EFS access point

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-sigs/aws-efs-csi-driver#124]
**Is your feature request related to a problem? Please describe.**
EFS launched access point: https://aws.amazon.com/about-aws/whats-new/2020/01/amazon-elastic-file-system-introduces-efs-access-points/. This provides fine granular access of efs mount point using IAM roles. We need to integrate this with the driver.

**Comment by adammw** [comment]
I believe this is just the mount.efs helper installed in the docker image is too old and needs to be updated.

**Comment by leakingtapan** [comment]
Several things needed for this to happen:
* upgrade to the latest efs mount helper (as @adammw mentioned)
* add new field for access point ID in storageclass 
* pass the access point ID to node service for efs volume mount
* efs csi node service needs to assume the role of container that is consuming the volume (this is the challenging part). Several things needs to happen here:
  * csi node service needs to read the role arn of the container that is consuming the volume
  * csi node service needs to assume the above using assume role with the driver IAM identity

**Comment by adammw** [comment]
> pass the access point ID to node service for efs volume mount

This currently works (with an updated mount helper) with `mountOptions`, although from a user-interface point-of-view, is not obvious.

> efs csi node service needs to assume the role of container that is consuming the volume

If using the instance profile rather than container-dedicated IAM roles (less secure, but possible) I don't believe any extra logic is required as the mount helper will get the credentials from the instance metadata endpoint.

**Comment by MrNorm** [comment]
Hello! I was just wondering where this issue got to? I'd love to be able to use IAM for our EFS volumes. Thanks

**Comment by leakingtapan** [comment]
@MrNorm could u add more details about ur use cases?

**Comment by MrNorm** [comment]
@leakingtapan Sure thing - I'm looking to shift a number of web assets over to our EKS stack. Each web asset could have replicated pods and they all need access to a shared filesystem.

EFS + IAM at container/pod level, combined with access point mount options seemed a really good fit for this, as we can mount various EFS 'access points' and ensure the policy only allows access to containers/pods that fit the policy attached to that role and service worker. 

Thanks!

**Comment by asadullahrao** [comment]
Can anyone share the access policy with access endpoint, which i will add in my efs file policy. which ultimately accessible to my tasks.

**Comment by wongma7** [comment]
> Can anyone share the access policy with access endpoint, which i will add in my efs file policy. which ultimately accessible to my tasks.

You should only need to give the driver ClientMount permissions to your access point https://docs.aws.amazon.com/efs/latest/ug/iam-access-control-nfs-efs.html. As noted above if your driver doesn't have its own aws identity it will inherit the instance profile of the node it's running on

RE: IAM policy of the driver:

I think we should keep the current behavior of the driver where it implicitly expects to have permission to ClientMount things access points, whether via instance policy+role or a dedicated policy+role (and document it with examples). It's a bit more secure than having the driver assume applications' roles because presumably the application has additional permissions like ClientWrite that the driver doesn't need and shouldn't receive.

Unless users trust the driver to have ClientMount for wildcard access points, they would have to maintain a policy that lets it ClientMount their various access points. But either way I think it's preferable to having to maintain a policy that lets the driver AssumeRole their various applications' roles.

RE: having a dedicated field vs a mountOption.

>  This currently works (with an updated mount helper) with mountOptions, although from a user-interface point-of-view, is not obvious.

I don't like that it's non-obvious/discoverable but I would prefer to continue respecting mountOptions versus adding a dedicated field and dealing with potential conflicts...it's kind of like how "encryption in transit" means add option tls but an encryptionInTransit bool field would be much nicer.

**Comment by wongma7** [comment]
The best option which I didn't see earlier would be to respect node publish secrets https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/127 and assume the role in the secret only at mount time

**Comment by leakingtapan** [comment]
How is it going to work as the driver needs to handle multiple volumes, and each volume requires a different permission to be mounted? And also how about is secret rotation if secret object is used? What if customer need to use IAM for SA, would it cause any conflict?

**Comment by robwithhair** [comment]
Really looking forward to this functionality as my cluster is currently failing Pen Test due to lack of Access Point usage.

**Comment by ossareh** [comment]
@robwithhair It seems possible to access EFS with access points; indeed the example here works almost perfectly for me: https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/examples/kubernetes/access_points

What isn't clear to me is how to specify a service account for the driver; ultimately I want the driver to be able to use "elasticfilesystem:ClientRootAccess" to mount the access point with a root UID / GID - which seems possible according to: https://docs.aws.amazon.com/efs/latest/ug/efs-access-points.html#enforce-identity-access-points - @wongma7, in your prior comment you suggested this sort of permission should be specified in the instance profile - is this because CSI is working at the kubelet level?

**Comment by leakingtapan** [comment]
related to #167

**Comment by 2uasimojo** [comment]
The original issue here does seem obsolete given https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/examples/kubernetes/access_points. If there are still permission/usability problems, suggest opening a new more specific issue.

**Comment by jackivanov** [comment]
Is there any progress on segregated service accounts policies for containers?
