### ISSUE TITLE
Typo in Helm chart values file podLabel should be podLabels

### ISSUE THREAD

**Issue by ismaillatona** [kubernetes-sigs/aws-efs-csi-driver#1319]
/kind bug

**What happened?**
Pod labels are not set on the controller pods.
While looking at the default values file there is a typo at `controller.podLabel` it should be `controller.podLabels` as referenced in the templates
**What you expected to happen?**
I expected pod labels to be set on the controller pods
**How to reproduce it (as minimally and precisely as possible)?**
Setting podLabel value does not set the controller pod labels
**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Please also attach debug logs to help us better diagnose**

- Instructions to gather debug logs can be found [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting)

**Comment by seanzatzdev-amazon** [comment]
Thank you for bringing this to our attention @ismaillatona 

We are working on merging the following PR which addresses this: https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1305

**Comment by r-yabyab** [comment]
The chart value's controller.podLabel works for me. Couldn't get controller.podLabels to work.

**Comment by chris-bosman** [comment]
A few more details:

In values.yaml, [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/2c80cae9770ee00018df6242fac33108f04bd107/charts/aws-efs-csi-driver/values.yaml#L66), the name of the variable is `PodLabel.`

But it does not appear as though this will ever modify the tags on the deployed pods, since the code for the pod's labels [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/2c80cae9770ee00018df6242fac33108f04bd107/charts/aws-efs-csi-driver/templates/controller-deployment.yaml#L29-L31) references a variable called `PodLabels`.

The two files need to be reconciled to agree on the variable name. The simplest would simply be renaming `controller.PodLabel` to `controller.PodLabels` to agree with what's currently in the controller deployment definition.
