### ISSUE TITLE
Pod disruption budget

### ISSUE THREAD

**Issue by sstarcher** [kubernetes-sigs/aws-efs-csi-driver#1397]
**Is your feature request related to a problem? Please describe.**
To prevent the schedule from terminating all aws-efs-csi-driver pods at the same time

**Describe the solution you'd like in detail**
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/901

**Comment by sherifabdlnaby** [comment]
I would have opened a PR for this but found that https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1404 already exists but just needs to be rebased to be mergeable. 

We recently faced an incident because we didn't have PDB on the EFS Controller, we could add it outside the chart lifecycle, but doing it via the Chart is the right way of doing it 🙏🏻
