### ISSUE TITLE
Please provide an official aarch64 image for use on m6g, a1

### ISSUE THREAD

**Issue by tsarna** [kubernetes-sigs/aws-efs-csi-driver#184]
**Is your feature request related to a problem?/Why is this needed**
The 64-bit ARM-based m6g family is generally available now and provides very attractive price/performance (and the older a1 has been available for a while). It should be possible to use these ARM-based instances just as easily as amd64, and to that end there should be official images on Docker hub for aarch64 as well.
/feature

**Describe the solution you'd like in detail**
Build the current version on ARM as well and offer it on Docker Hub alongside the existing amd64 images.

**Describe alternatives you've considered**
It should be possible to build my own image easily enough, and I may end up doing that in the interim, but it's an extra hassle, and I feel AWS should provide aarch64 support as a first-class feature given that they now have two GA amd64 instance type families on offer.

**Comment by leakingtapan** [comment]
Similar request: https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/111

**Comment by KorvinSzanto** [comment]
Is there a workaround today beyond building my own image?

**Comment by lexagigabit** [comment]
Just a comment for whoever is here struggling with the same issue, I just saw that the github workflow for this project contains arm64 instructions, I used the master branch and it just worked perfectly
Take into account that in case you tried to use a link from AWS Docs with the 1.1 release and it failed, you should delete all the `efs-csi` related stuff running, including the pods, which are stuck in error state, because that is what I did not do and it did not work, then I cleaned it up and it worked. 
So check there is nothing efs-related anywhere, then just
`kubectl apply -k "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/ecr/?ref=master"`
And it works

**Comment by dbuos** [comment]
Does anyone know if the support for aarch64 already released and stable?

**Comment by wongma7** [comment]
v1.3.2 is multiarch. The sidecar images (as installed in the daemonset/deployment by the helm chart/kustomize) should be multiarch as well.
```
~ $ docker manifest inspect amazon/aws-efs-csi-driver:v1.3.2
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1582,
         "digest": "sha256:42fd397df352973e06c9cb8939cd031f205b42dc84590b8ded8eb6709fe6505b",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1582,
         "digest": "sha256:cee19124fc7c913a084588a77f07708b028e5c555f3341db5558b2d1853b037e",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
   ]
}
```

wrt to stability, it does not undergo the same amount of testing as the amd64 variant because our CI only exercises the amd64 environment. But we did of course manually test it on arm before releasing it, and it is the same code at the same version 1.3.2.

**Comment by dbuos** [comment]
Thanks for your reply @wongma7 !
