### ISSUE TITLE
Using the latest yaml install file + v0.3.0 driver no longer works

### ISSUE THREAD

**Issue by jqmichael** [kubernetes-sigs/aws-efs-csi-driver#191]
/kind bug

**What happened?**
issue is our command to install efs driver is downloading an image which is not working. 
kubectl apply -k "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master"

MountDevice failed to create newCsiDriverClient: driver name efs.csi.aws.com not found in the list of registered CSI drivers

**What you expected to happen?**

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Comment by jqmichael** [comment]
We added a hostpath to /etc/amazon/efs/ which override the efs-utils.conf file. The driver from master branch will install the config file itself, but since you are using a stable version of the driver, that didn't happen.

https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/deploy/kubernetes/base/node.yaml#L102

I think we should start branching the yaml installment of the driver.

**Comment by wongma7** [comment]
We can maintain overlays for each version in master. And let stable always be a copy of the latest stable release. We should not change stable until after a new release when we do the post-release stuff, update the README etc.: https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/140/

**Comment by wongma7** [comment]
Let's revert ad02e03 for now. Basically we should never touch stable overlay except in post-release stage where we will copy changes from dev overlay to stable overlay.

**Comment by omriarieli** [comment]
Hi, FYI i am getting validation errors when installing with helm3 on eks kubernetes 1.15

null_resource.efs_csi_driver (local-exec): Error: rendered manifests contain a resource that already exists. Unable to continue with install: CSIDriver "efs.csi.aws.com" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "aws-efs-csi-driver"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "default"

the part about CSIDriver existing is irrelevant i had to manually delete it since it was installed before with kubectl.
also after the helm chart is installed it reports it is installed in default namespace using helm ls, even though it is installed in kube-system namespace

**Comment by wongma7** [comment]
The helm chart is still not quite right. I think there needs to be an if statement here https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/helm/templates/daemonset.yaml#L111 excluding it if the version is <= v0.3.0

**Comment by dec14** [comment]
The installation still isn't working

**Comment by KorvinSzanto** [comment]
I'm using CDK to load in this driver using helm and I'm getting the error shown above:
My `HelmChartOptions` object is:
```ts
{
    chart: 'aws-efs-csi-driver',
    repository: 'https://kubernetes-sigs.github.io/aws-efs-csi-driver/',
    release: 'aws-efs-csi-driver',
    namespace: 'aws-efs-csi-driver'
}
```
