### ISSUE TITLE
NodeGetCapabilities logged to stderr instead of stdout

### ISSUE THREAD

**Issue by cbighea** [kubernetes-sigs/aws-efs-csi-driver#252]
/kind bug

**What happened?**
The aws-efs-csi-driver pods have the following item showing up in stderr in Datadog monitoring, which doesn't seem to be an error:
`I0913 12:09:11.322490       1 node.go:226] NodeGetCapabilities: called with args`

**What you expected to happen?**
I expected this to be logged to stdout

**How to reproduce it (as minimally and precisely as possible)?**
Just followed the normal setup instructions, nothing special.

**Anything else we need to know?**:
I think this output should instead go to `/proc/1/fd/1` though I may be wrong.

**Environment**
- Kubernetes version (use `kubectl version`): 1.17
- Driver version: 1.0.0

**Comment by keifgwinn** [comment]
Does it even need to log this at all? It's the single largest message count on my system, hundreds of thousands of lines of useless logging.

**Comment by edvsuperbrave** [comment]
We get these entries thousands of times in our logs too:

main.go:68] Health check succeeded
connection.go:184] GRPC error: <nil>
connection.go:183] GRPC response: {}
connection.go:181] GRPC request: {}
connection.go:180] GRPC call: /csi.v1.Identity/Probe
main.go:50] Sending probe request to CSI driver "efs.csi.aws.com"

We sent out k8s logs to DataDog which marks it as errors. Probably because they're also sent to stderr. It's useless data and I'd rather see this gone completely.

The process should only output something when the probe request / health check fails. Apart from that, it should keep quiet, IMHO.

It is not only annoying as the logs are littered with incorrect errors, it also adds to the costs of transmitting, parsing. storing and monitoring the logs of our k8s system.

Info on what produces the errors:

kube_daemon_set: efs-csi-node
kube_app_instance: aws-efs-csi-driver
kube_app_name: aws-efs-csi-driver
kube_namespace: kube-system
pod_name: efs-csi-node-qf25c
kube_container_name: liveness-probe

**Comment by wongma7** [comment]
klog https://github.com/kubernetes/klog logs to stderr by default.

I think the issue is the helm chart defaults to loglevel 5 https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/values.yaml#L52 which is too high. These messages are set at level 4/5 which is meant for debugging, the chart doesn't need to default that high
