### ISSUE TITLE
Can't find chart v0.2.1

### ISSUE THREAD

**Issue by ahmad-hamade** [kubernetes-sigs/aws-efs-csi-driver#265]
/kind bug

**What happened?**
Can't find the latest chart version available from the repo https://kubernetes-sigs.github.io/aws-efs-csi-driver/

**What you expected to happen?**
I should see the latest chart v0.2.1

**How to reproduce it (as minimally and precisely as possible)?**

helm repo add aws-efs-csi-driver https://kubernetes-sigs.github.io/aws-efs-csi-driver/
helm search repo aws-efs-csi-driver

Return chart version 0.1.0

**Comment by JonathanLachapelle** [comment]
Also helm chart v0.2.0 is not present

**Comment by ahmad-hamade** [comment]
Also the chart release 1.0.0 is missing. 😩

**Comment by JonathanLachapelle** [comment]
There's probably a pipeline not being triggered. I'm not sure exactly of the process to package and publish the helm charts

**Comment by othillo** [comment]
It seems that the Helm repo index (https://kubernetes-sigs.github.io/aws-efs-csi-driver/index.yaml) is not updated.

As a workaround I cloned this repo at v1.0.0 and installed it from there:

```
git clone --depth 1 --branch v1.0.0 https://github.com/kubernetes-sigs/aws-efs-csi-driver.git
helm install aws-efs-csi-driver ./aws-efs-csi-driver/helm
```

**Comment by pieeri** [comment]
Related to the recent upgrades in EKS (https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/267), is there a timeline in resuming the Helm chart pipeline?

Current EKS versions (>=1.17) require the changes included in https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/270. Sadly, for continuous deployment (via e.g. Terraform), the current chart doesn't offer the possibility to modify the helm installation hooks.

**Comment by agrahamlincoln** [comment]
There have been changes to both the EFS CSI driver and the helm chart which fix critical issues on installation. **Please publish a new helm chart, and update the repository.**

I took a quick stab at updating myself, and it seems that outside contributors could not provide this configuration ourselves - the newest helm chart needs to be available for download via github releases to properly update the repository index.yaml

the aws-efs-csi-driver github pages are hosted on the `gh-pages` branch, which is currently set to helm chart [version 0.1.0](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/06d3694fdbf5fe484e14ccd83cecd07d64e4d433/index.yaml)

it looks like when the v1.0.0 release was cut, @wongma7 updated the helm chart index, but did not merge the changes to `origin`. Here is the [0.2.0 helm chart update](https://github.com/wongma7/aws-efs-csi-driver/commit/0e368a65291499af5401c72640e43792c67f84ab), still "lost" in @wongma7 's fork.

Regardless, there are newer changes to the helm chart after the v1.0.0 release that include:

- Fixes for #270, #267, #253
- Update to v1.0.0 images

If I were a maintainer here are the steps I would perform to get this up to date (hopefully this serves as a checklist or guide for maintainers)

- [ ] Merge @wongma7 's v1.0.0 chart update into `origin/gh-pages` - _will allow users to at least update to the newest EFS CSI driver images_
- [ ] Create a v1.0.1 github tag/release with the newest `helm-chart.tgz` included for recent fixes
- [ ] Update `origin/gh-pages` via `helm repo index` to publish the latest helm chart to the helm repo.

@wongma7 @leakingtapan any chance on getting this updated soon?

**Comment by wongma7** [comment]
Thank you for the deep dive, this fell off my radar.

Recently somebody contributed a chart-releaser github action to automate chart updates and github releases of chart updates to the ebs repo so I am going to follow that pattern.
ref:
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/.github/workflows/helm-chart-release.yaml

Ping me on slack if you do not sewe movement on this issue by end of week, IIRC it got stalled simply because we couldn't figure out how the helm hash changed, but in practice helm does not even use that hash to verify chart/download integrity (yet) so I'll just ignore it if it happens again.

**Comment by krmichel** [comment]
@ahmad-hamade @JonathanLachapelle @othillo For some clarity around this issue.  PR #292 should fix this in the short term by making the app version 1.0.0.  @wongma7's PR #291 should fix it on a permanent basis.  Some of the versions that are referenced on this issue are the version of the driver and not the chart.  The chart had been at version 0.1.0 since the initial commit of it here: https://github.com/kubernetes-sigs/aws-efs-csi-driver/commit/8ca65933fea01cd89f545ec47914aa5a8b8dc227#diff-ab3e9fcf0ffe762ed2805586f2e116f0c38db08c3b34d6ba2cfa90e871a1d918R5 and stayed that way through the publishing of version 1.0.0 of the driver (it have been updated since but not published anywhere).  One of the downsides of the way the chart publishing is being done in this repository is that it is published when the driver is and not when the chart is changed.  This results in there being confusion about versions and can make it more confusing to generate an index.yaml.  The best way that I am aware to generate an index.yaml is using the `helm repo index` command.  It has flags for dealing with the url of the download for the chart and another flag for merging in a previously generated index.  I hope this provides some background information that might be helpful in the future.  It should no longer be an issue for this project once these couple of outstanding PRs are merged.  The action will create releases that are specific to the chart when the chart is changed and match the charts version and update the index to know about those versions automatically.

**Comment by wongma7** [comment]
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/292 has merged so now chart version 0.1.0 refers to appVersion/driver version 1.0.0.

https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/291 is still in progress since I last commented, I need to rebase it and test it in my fork.

**Comment by steers** [comment]
Now that PRs #292 and #291 have both been merged, is there anything left to be done for this issue? lgtm

```
% helm repo add aws-efs-csi-driver https://kubernetes-sigs.github.io/aws-efs-csi-driver/
"aws-efs-csi-driver" has been added to your repositories
% helm search repo aws-efs-csi-driver
NAME                                 	CHART VERSION	APP VERSION	DESCRIPTION
aws-efs-csi-driver/aws-efs-csi-driver	1.1.0        	1.1.0      	A Helm chart for AWS EFS CSI Driver
```

**Comment by agrahamlincoln** [comment]
LGTM! Thanks for getting this over the line, I'm updating my helm deployments now to the latest chart :)

**Comment by wongma7** [comment]
thanks for patience all.
