### ISSUE TITLE
Dynamically create file systems

### ISSUE THREAD

**Issue by wochanda** [kubernetes-sigs/aws-efs-csi-driver#310]
With the newly introduced [dynamic provisioner](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/274), the driver lets users associate an EFS File System (FS) with a Storage Class (SC), with Persistent Volume Claims (PVC) resulting in provisioning of EFS Access Points underneath that file system with unique directories/UIDs/GIDs for privacy. Currently EFS has a hard limit of 120 APs per FS, so in environments that need more than 120 volumes multiple FSs need to be created and associated with multiple SCs.

We can enhance this by allowing the provisioner to both create file systems and manage multiple file systems per storage class, that way users can provision up to thousands of PVCs per SC without manual intervention. 

The SC definition could look something like this (fields added to control :

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-fs-ap
  maxFileSystems: 50
  maxApsPerFileSystem: 100 // 50 FS * 100 APs = 5k potential volumes
  fileSystemMode: generalPurpose // (generalPurpose or maxIo)
  mountTargetSubnets: [] //input subnet ids (one per AZ) for us to create mount targets, if not specified use default subnets
  securityGroup: sg-123456 //SG to apply to mount targets, default to default security group
  throughputMode: bursting // (bursting (default) or specify amount of provisioned throughput, e.g. 100 for 100MB/s)
  lifecyclePolicy: 7 // default 30d, 0 to turn off lifecycle management
  autobackup: true // default true, false to turn off AWS Backup
  tags: [] // tags added to both FS and AP
  gidRangeStart: "1000"  //Optional
  gidRangeEnd: "2000"   //Optional
  directoryPerms: "777"  //Optional
  basePath: "/data"  //Optional

**Comment by gabegorelick** [comment]
This would be useful for more isolation than what access points provide.

**Comment by iusergii** [comment]
Am I correct that this would allow having the same user experience as with EBS?

**Comment by mimmus** [comment]
The hard limit of 120 access points can be extremely limiting for using it in Kubernetes since that would essentially mean you're limited to 120 PVCs. Then you'll need to create another EFS with another storage class to scale further.... I think it defeats the purpose of the scalability aspect of EFS and will require manual intervention.

**Comment by mimmus** [comment]
It's an AWS hard-limit based on use cases.
I had a call with EFS engineers, they asked for details abouth this specific use case but don't give me any timeframe.

**Comment by itsvshreyas** [comment]
We even have a use case to spin up more than 1000 Persistent Volumes. AWS does not support nfs-subdir-external-provisioner. Switching to AWS-CSI, which supports dynamic provisioning, now has its own issues with its hard limit. We have even had a case opened with EFS Engineers to see if we can get any changes to this in future versions at least. We will have to wait and see.

**Comment by Almenon** [comment]
@leakingtapan Can we re-open this and freeze the lifecycle please? I think it's clear based on the number of 👍 that this is desirable. This would be ranked the second most requested feature by +1's if it were open.

To give some additional context, cost tracking is important to us, so I'd like to be able to create different EFS filesystems for different cost categories, instead of creating a single one and reusing access points.

But you could create multiple filesystem with Terraform. I have three reasons why I'd prefer the driver:
1. That way everything (filesystem, access point, PV, PVC, PV mount) is grouped together
2. It matches the behavior of EBS CSI driver
3. Personally, I prefer using Kubernetes over Terraform

**Comment by ns-mkusper** [comment]
I'd also like to request re-opening and for the lifecycle to be frozen for the same reasons that @Almenon mentioned.
