### ISSUE TITLE
Node.yaml should allow specifying serviceaccount (release 1.1)?

### ISSUE THREAD

**Issue by esalberg** [kubernetes-sigs/aws-efs-csi-driver#316]
/kind bug

**What happened?**
I was testing service account settings with release 1.1 (dev overlay).  After updating serviceaccount-csi-controller.yaml, the serviceAccountName setting in controller.yaml worked appropriately.  However, the pods from node.yaml were not using the serviceAccountName (until I added that line to the template spec).

**What you expected to happen?**
Could you please confirm whether node.yaml also needs to assume a role for IRSA to work successfully?  Our goal is to specify a specific role for the EFS CSI driver (e.g. role.efs) and then add that to the EFS filesystem policies for access.  That way, we won't have to update the EKS worker node role in the filesystem policies every time we update an EKS node group.

I wanted to check prior to release 1.1 just to make sure this wasn't overlooked.  Please close this ticket if node pods don't need to assume the role, just the controller pods.

Note: My IRSA testing ultimately failed anyway, I'm assuming due to issue #290 (Upgrade to efs-utils v1.28.2).  Or is the service account supposed to work / be assumed successfully for EFS even without the efs-utils update?
 
**How to reproduce it (as minimally and precisely as possible)?**
 - Update serviceaccount-csi-controller.yaml (or use Kustomize to override, I'm assuming) to set  the role-arn annotation
 - Deploy with kubectl apply -k dev/ (from the overlays directory)
 - Check the pods and see that the SA is in use for the controller pods but not the node pods (set to default role)

 (Even after I added the service account by hand to the node.yaml template spec, NewClientConnections from an app pod were rejected due to use the default role - which as I noted could be due to the efs-utils version.  I have not tried manually updating efs-utils in the pod to confirm.)

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): v1.18.9-eks-d1db3c
- Driver version: 1.1 dev (release-1.1 branch)

**Comment by wongma7** [comment]
We have included an example controller serviceaccount because it's ALWAYS needed but we are lacking an example node serviceaccount because it's only sometimes needed. We don't intend for both controller and node to use the same serviceaccount.

The example service account is provided for the controller only because the controller MUST have permission to create and delete access points. Documentation about the controller is coming: https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/297/files .

By default the node plugin won't need any special IAM permissions, but if you've configured a policy for  EFS filesystem then yes it needs to be included in that policy somehow: https://docs.aws.amazon.com/efs/latest/ug/iam-access-control-nfs-efs.html. Like your policy would have to reference the role you intend to give node plugin and then you would give the node plugin that role via IRSA. We haven't provided any examples of all this though

**Comment by wongma7** [comment]
/assign
 
Will add a node equivalent:

"serviceaccount-csi-node.yaml " to kustomize and helm
