### ISSUE TITLE
How to specify the EFS ID

### ISSUE THREAD

**Issue by prithulagta** [kubernetes-sigs/aws-efs-csi-driver#319]
Hi - Currently running into an issue, where I am getting the below error from pod in statefulset:

Normal   ExternalProvisioning   PersistentVolumeClaim   waiting for a volume to be created, either by external provisioner "efs.csi.aws.com" or manually created by system administrator

To give a background:
1. I have provisoned an EFS and have the correct SG added to it.
2. I have the efs-csi-node daemontset with pods running
3. I have a storageclass which looks like below:
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
    name: efs-sc
   provisioner: efs.csi.aws.com
4. The volumeclaimtemplate section in the statefulset looks like below:
    volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        app: sample
      name: homedir
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 1Mi
      storageClassName: efs-sc
      volumeMode: Filesystem

Now the issue is where do I specify the EFS ID. In the retired version of  efs-provisioner, you would specify the EFS ID via an environment variable FILE_SYSTEM_ID.

The example https://raw.githubusercontent.com/kubernetes-sigs/aws-efs-csi-driver/master/examples/kubernetes/statefulset/specs/example.yaml suggest to create the PVC and PV separately. However for a statefulset with multiple replicas, it will be a problem, as all pods will use the same PVC.
Thanks.

kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:26:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Driver Version: 
image: aws-efs-csi-driver/v1.0.0
  sha: sha256:94924e549150a9cec08912f8e7a44c9625e0de9cc4544c0c8d9fef48b1029acf

csi_node_driver_registrar:
  image: csi-node-driver-registrar/v1.3.0
  sha: sha256:9622c6a6dac7499a055a382930f4de82905a3c5735c0753f7094115c9c871309

livenessprobe:
  image: livenessprobe/v2.0.0
  sha: sha256:ac12fcab5bd2550d580a83b531ccea0f446ae16e5c9ed29e9c676e5ed9f4e264

**Comment by wongma7** [comment]
The statefulset use-case assumes that there will be an external provisioner to dynamically create PVs for each of your PVCs. However, support for this has not been released as of the latest version (1.1.0)

**Comment by prithulagta** [comment]
Thanks for your response. However even if you provision the PVs and PVS separately, how will one link them to the individual pods belonging to the statefulset?

**Comment by wongma7** [comment]
I don't think there is currently a convenient way to link PV->PVC->Pod. You have very limited ways to influence what PV and thus what EFS FSID a Pod mounts from the Pod perspective, there are no args or anything to explicitly pass the ID.

Say you have pod-0 and pod-1, and you want to link them in such a way that pod-0 always uses pv-0 (fsid:/path-0) and pod-1 always uses pv-1 (fsid:/path-1).
pod-0->pvc-0->pv-0 (fsid:/path-0)
pod-1->pvc-1->pv-1 (fsid:/path-1)

If you pre-create pvc-0 and pv-0, and force them to bind to each other by using claimRef and volumeName https://stackoverflow.com/questions/34282704/can-a-pvc-be-bound-to-a-specific-pv, then the statefulset should "adopt" pvc-0 instead of trying to create a new one. Of course this is labour intensive and not scalable.

I think the dynamic provisioning feature will satisfy your use-case. You will be able to specify the FSID in the StorageClass like https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/297/files#diff-0b5ca119d2be595aa307d34512d9679e49186307ef94201e4b3dfa079aa89938R30. Then specify in your statefulset's pvc template the storageClass. Then when you scale up the statefulset, each pvc will be created and get provisioned a new PV that represents a different access point/path within that FSID.

**Comment by prithulagta** [comment]
Thank you for the detailed response. Much appreciated. Will do the workaround as you suggested. However will keep an eye on the PR, to when it gets' merged.
