### ISSUE TITLE
Please publish the EFS image to public.ecr.aws or some other AWS-hosted ECR repository

### ISSUE THREAD

**Issue by diranged** [kubernetes-sigs/aws-efs-csi-driver#456]
**Is your feature request related to a problem?/Why is this needed**

Given Docker Hub's rate limiting, and AWS now hosting `public.ecr.aws` as a public ECR endpoint, I would like to see the EFS Driver image hosted there like most of the other images. Alternatively something like `k8s.gcr.io` or some other un-throttled Docker hosting service.

/feature

**Describe the solution you'd like in detail**

Ideally the images would be hosted in public ECR repositories like `public.ecr.aws`.

**Describe alternatives you've considered**

For now we are 'vendoring' the image into our own ECR repository - but that is not ideal and increases the overhead for us when we're upgrading releases.

**Comment by wongma7** [comment]
we do publish to private ecr but it's a bit hidden: https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/deploy/kubernetes/overlays/stable/ecr/kustomization.yaml#L7, does that work for you?

I do want to eventually push to public ECR and GCR as well but I'm not actively working on it. we added GCR pushing to ebs shortly after docker hub introduced their throttling, so definitely it's feasible to repeat here. https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/cloudbuild.yaml

I intend to create an umbrella issue to sort out our image distribution inconsistencies, the lack of public  ecr is just one issue.

**Comment by diranged** [comment]
> we do publish to private ecr but it's a bit hidden: https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/deploy/kubernetes/overlays/stable/ecr/kustomization.yaml#L7, does that work for you?

Ah that's great! Is that repository available in all the regions - or just Oregon? 

> I do want to eventually push to public ECR and GCR as well but I'm not actively working on it. we added GCR pushing to ebs shortly after docker hub introduced their throttling, so definitely it's feasible to repeat here. https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/cloudbuild.yaml

:+1:

> I intend to create an umbrella issue to sort out our image distribution inconsistencies, the lack of public ecr is just one issue.

For what it's worth, I would like to see the EBS and EFS drivers merged into one helm chart (so it runs as 1 pod). That would simplify deployment a lot and reduce the overhead of having _two_ pods on every single host just for the purpose of managing storage volumes, ya know? I know that's unrelated to this issue.

**Comment by wongma7** [comment]
it should be available in all regions that EKS is available in, including opt-in. If it's missing from any that's a bug. 

>  For what it's worth, I would like to see the EBS and EFS drivers merged into one helm chart (so it runs as 1 pod). That would simplify deployment a lot and reduce the overhead of having two pods on every single host just for the purpose of managing storage volumes, ya know? I know that's unrelated to this issue.

we don't have plans to do this but I understand. There being two DaemonpSets is very hard to avoid due to how csi works. But in terms of the controller/Deployment, it is a bit wasteful to run copies of the same sidecar e.g. external-attacher. Versus in the in-tree/non-CSI model, there is just one attachdetach controller for all plugins to share.

Generally speaking, IMO the helm charts and associated release engineering are the biggest pain points both for users and maintainers. There have been a lot of contributions to clean them up though so hopefully even if ebs and efs can't be merged into one chart they will at least be consistent

**Comment by aliusmiles** [comment]
well, looks like 1.3.0 wasn't pushed to 'hidden public ECR' just yet:

```sh
Failed to pull image "602401143452.dkr.ecr.eu-north-1.amazonaws.com/eks/aws-efs-csi-driver:v1.3.0": rpc error: code = Unknown desc = Error response from daemon: manifest for 602401143452.dkr.ecr.eu-north-1.amazonaws.com/eks/aws-efs-csi-driver:v1.3.0 not found: manifest unknown: Requested image not found
```

I've followed [official docs](https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html) but just had to revert to default docker hub image.

seems kinda weird with sidecars from public.ecr.aws and efs-csi-driver from docker hub and official docs saying "use region-tied ECR which we do not update in time" ;) let me guess, different orgs/teams responsibility, etc? :)

Joking aside, GCR do seem to be a better option.

P.S. Should I create separate issue for ecr v1.3.0 not available?

**Comment by wongma7** [comment]
@aliusmules yes please create an issue.

There are technical and human reasons that the push to this official EKS private ECR account 602401143452 always lags behind push to docker hub. But a lag of over a day is not normal. Basically in terms of the technical side, we can't trigger the push from a github actions like we can for docker hub because github actions can't do the fancy regional-replication logic we need. and for human side, somebody has to go manually trigger the push, and if that push failed for whatever reason it needs more manual intervention.

**Comment by aliusmiles** [comment]
@wongma7 Done: #484

**Comment by RyanStan** [comment]
Image is now hosted on public aws ECR:
https://gallery.ecr.aws/efs-csi-driver/amazon/aws-efs-csi-driver
