### ISSUE TITLE
support dynamic recovery of PV/PVCs from existing file system

### ISSUE THREAD

**Issue by wochanda** [kubernetes-sigs/aws-efs-csi-driver#476]
The CSI driver should support a mechanism to recover from a disaster affecting both the Amazon EFS file system and the Kubernetes cluster (e.g. accidental stack delete). Using AWS Backup, users can backup and restore Amazon EFS file systems. However, the CSI driver does not yet have an automated way to recreate the PVs and PVCs of a restored file system, which would also involve recreating the underlying Access Points.

One way to accomplish this would be to:
1. Modify the CSI driver to persist PV/PVC configuration to the underlying file system.
2. Add a flag to EFS storage class that will read the PV/PVC configuration from the file system, and recreate any PVs and PVCs  that were previously created.

With this in place, users recreating their K8S+EFS environment would:
1. Restore EFS file systems from backup
2. Recreate the K8S environment 
3. Reconfigure the EFS storage classes with recover=true flag set, which will recreate PVs/PVCs
4. Redeploy applications. When those applications attempt to create PVCs they will see that they have already been created, and be able to attach them to pods.

Please +1 if you'd be interested in this, and comment if the suggested approach wouldn't fit in your DR approach.

**Comment by kycrow32** [comment]
Just a note that this ticket was born out of this support ticket:
https://forums.aws.amazon.com/thread.jspa?threadID=340086

**Comment by hppsc1215** [comment]
We also interested in such functionality. Currently we do not have a good way to backup and restore efs pvs.

**Comment by vakkursw** [comment]
I am also looking for something like this where I can restore the PVs in different EKS cluster

**Comment by indra0007** [comment]
We are looking for this feature too

**Comment by shyamsubbu** [comment]
why all needed things are closed in K8. efs-csi-driver ? EFS backup and restore PVC is essential for K8 aws recovery . 
First there is no snapshot support in EFS CSI Driver
Second, there should be a staright forward way to restore pv pvs with fileaccess points with AWS backup restore

**Comment by dale-c-anderson** [comment]
Though dynamic recovery would be a brilliant feature, I don't know of any sane/safe way it could be automated. Especially considering the hoops I had to jump through to actually accomplish a recovery.

When trying to modify a pv, the error I ran into was that they are immutable after creation, so it seems like Kubernetes itself systematically prohibits this kind of feature from ever seeing the light of day.

I did work around it though, in a slightly hair-raising way. In order to make the cluster use the replacement EFS instance, for each affected pv, I had to:
- back up the pv to yaml,
- replace the old EFS dns address with the new address in the yaml file,
- delete the original pv, and patch the finalizers to null so it could actually finish terminating,
- from my patched yaml file, recreate the pv with the exact same IDs the old one had, but with the new EFS address.

This turned out to be scriptable, which was at least some small mercy:

```shell
#!/bin/bash
set -eu -o pipefail
############################################
########### USE AT YOUR OWN RISK ###########
############################################
NS=safety-filter-so-reckless-copy-pasters-dont-mangle-their-own-stuff-and-then-blame-me
SC=bulk  # The storage class that our efs pv's use is named 'bulk' so it was easy to filter on
for ID in $(kubectl get pv |grep "$SC" | grep "$NS" | awk '{print $1}'); do
  kubectl get pv "$ID"  # Spit this out to console, for later identification of pods that will need restarting
  set -x;
  kubectl patch  pv "$ID" -p '{"spec":{"persistentVolumeReclaimPolicy":"Retain"}}';  # Just paranoia here. This wasn't actually needed.
  PATCHED_PV="patched-pv-$ID.yml";
  kubectl get pv "$ID" -o yaml  | sed 's/fs-OLD-INSTANCE-ID.efs.ca-central-1.amazonaws.com/fs-NEW_INSTANCE_ID.efs.ca-central-1.amazonaws.com/' > "$PATCHED_PV" ;
  kubectl delete pv "$ID" --wait=false;
  kubectl patch pv "$ID" -p '{"metadata":{"finalizers":null}}';
  kubectl wait --for=delete "pv/$ID" --timeout=300s;
  kubectl apply -f "$PATCHED_PV";
  set +x;
  echo ''
done
```
Once that was taken care of, I then had to force delete all the pods that were hung trying terminate, or hung trying to attach to the dead EFS instance.
