### ISSUE TITLE
Image v1.3.0 is not accessible on AWS ECR

### ISSUE THREAD

**Issue by aliusmiles** [kubernetes-sigs/aws-efs-csi-driver#484]
/kind bug

Image v1.3.0 is not pushed to AWS ECR 602401143452:

```
Failed to pull image "602401143452.dkr.ecr.eu-north-1.amazonaws.com/eks/aws-efs-csi-driver:v1.3.0": rpc error: code = Unknown desc = Error response from daemon: manifest for 602401143452.dkr.ecr.eu-north-1.amazonaws.com/eks/aws-efs-csi-driver:v1.3.0 not found: manifest unknown: Requested image not found

```

The same error in eu-west-1 region, haven't tested in others.

**Comment by wongma7** [comment]
It should now be published t o allregions including eu-north-1 

~ $ docker pull  602401143452.dkr.ecr.eu-north-1.amazonaws.com/eks/aws-efs-csi-driver:v1.3.0
v1.3.0: Pulling from eks/aws-efs-csi-driver
Digest: sha256:6b009b7d5bed8f3661dc9953ec4b6308cde14b1e17af9def09700aefc4c826b1
Status: Downloaded newer image for 602401143452.dkr.ecr.eu-north-1.amazonaws.com/eks/aws-efs-csi-driver:v1.3.0
602401143452.dkr.ecr.eu-north-1.amazonaws.com/eks/aws-efs-csi-driver:v1.3.0

Sorry for the delay. For transparency, the reason this time around ECR image didn't exist for hours after we already updated the kustomize overlay to refer to it is because we wanted to squeeze in a fix to make the v1.3.0 ECR image multiarch (amd64 + ARM). That didn't happen so v1.3.0 will be amd64-only.
