### ISSUE TITLE
Volume snapshot capability for the EFS CSI driver

### ISSUE THREAD

**Issue by bathina2** [kubernetes-sigs/aws-efs-csi-driver#511]
**Is your feature request related to a problem?/Why is this needed**
Currently the only mechanisms available to snapshot EFS volumes (or access-points) is through the AWS APIs. However, the logical next step would be to support snapshotting these volumes through the Kubernetes volume snapshot API  which is GA as of k8s version 1.20. Is there a plan to support this feature? Timeline?

/feature

**Describe the solution you'd like in detail**
Ideally it would work similar to the EBS CSI driver. Where one could create a VolumeSnapshot object and a snapshot would be created.

**Describe alternatives you've considered**
An alternative we are considering is to use the AWS EFS apis to take snapshots. However this is not easy, and restoring a snapshot would involve statically provisioning a new volume. It also removes the user from the kubernetes context.

**Comment by lukasz-mitka** [comment]
@bathina2 do you mind reopening this issue?

**Comment by asoltesz** [comment]
This is badly needed because point-in-time-consistent backups can only happen with snapshots.

There are now fairly sophisticated Kubernetes backup systems like Velero that supports consistent backups via Kubernetes Volume Snapshotting.

Due to the missing k8s snapshotting capability, Velero can only do inconsistent, filesystem based backups on EFS volumes (Restic).
