### ISSUE TITLE
Deployment via Manifest missing ServiceAccount "efs-csi-node-sa"

### ISSUE THREAD

**Issue by timothyaws** [kubernetes-sigs/aws-efs-csi-driver#519]
/kind bug

**What happened?**
When deploying the stable driver with command
```kubectl apply -k "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.3"```
Daemonset efs-csi-node is unable to launch nodes due to the "efs-csi-node-sa" Service Account not being available

```
Events:
  Type     Reason        Age                From                  Message
  ----     ------        ----               ----                  -------
  Warning  FailedCreate  7s (x12 over 18s)  daemonset-controller  Error creating: pods "efs-csi-node-" is forbidden: error looking up service account kube-system/efs-csi-node-sa: serviceaccount "efs-csi-node-sa" not found
```

**What you expected to happen?**
efs-csi-node Daemonset should be able to successfully launch pods.

**How to reproduce it (as minimally and precisely as possible)?**
```
kubectl apply -k "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.3"
kubectl describe daemonset efs-csi-node -n kube-system
```
**Anything else we need to know?**:
Helm deployment is fine, only deployment via manifest fails
**Environment**
- Kubernetes version (use `kubectl version`): n/a
- Driver version:n/a

**Comment by ab574** [comment]
What did you do to resolve this missing service account?

**Comment by timothyaws** [comment]
@ab574 My recommendation is to deploy via the helm chart if possible. Otherwise I haven't tested this but applying this yaml, should also work https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/deploy/kubernetes/base/node-serviceaccount.yaml

**Comment by tetsuo-miyakuni** [comment]
I have the same problem.

When I installed it last month with the following command, it was aws-efs-csi-driver:v1.3.1 and I was able to install it successfully.

```
kubectl kustomize \
    "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/ecr?ref=release-1.3" > driver.yaml
```


`kubectl describe daemonsets -n kube-system efs-csi-node `

```
Name:           efs-csi-node
~~~
  Containers:
   efs-plugin:
    Image:      602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-efs-csi-driver:v1.3.1
~~~
Events:                 <none>
```

`kubectl get pod -n kube-system efs-csi-node-mrswn -o yaml | grep serviceAccount`
```
  serviceAccount: default
  serviceAccountName: default
```

When I installed it today with the same command, it was aws-efs-csi-driver:v1.3.2, so I got an error because efs-csi-node-sa does not exist.


`kubectl describe daemonsets.apps -n kube-system efs-csi-node `
```
Name:           efs-csi-node
~~
  Service Account:  efs-csi-node-sa
  Containers:
   efs-plugin:
    Image:      602401143452.dkr.ecr.ap-northeast-1.amazonaws.com/eks/aws-efs-csi-driver:v1.3.2
~~
Events:
  Type     Reason        Age                  From                  Message
  ----     ------        ----                 ----                  -------
  Warning  FailedCreate  109s (x19 over 23m)  daemonset-controller  Error creating: pods "efs-csi-node-" is forbidden: error looking up service account kube-system/efs-csi-node-sa: serviceaccount "efs-csi-node-sa" not found

```
To avoid this, I installed the driver by specifying the version.

``
`kubectl kustomize  "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/ecr?ref=tags/v1.3.1" > driver.yaml`

**Comment by ab574** [comment]
ok thanks for both of your solutions. I am going to try testing the version as well as I like that better than my solution

for reference my solution, using terraform, was just to edit the DaemonSet yaml to use the controller-sa instead of the node-sa after the kubectl apply ran, which also worked.

#BEGIN EDIT EFS-CSI-NODE DAEMON SET
resource "kubectl_manifest" "csi-node" {
    yaml_body = <<YAML
***
      serviceAccount: efs-csi-controller-sa
      serviceAccountName: efs-csi-controller-sa
***

YAML
}

**Comment by salavessa** [comment]
Shouldn't the fix be as simple as adding `node-serviceaccount.yaml` to the `resources` element under `deploy/kubernetes/base/kustomization.yaml`?
I.e.:
```yaml
[...]
resources:
- node-serviceaccount.yaml
- node-daemonset.yaml
- csidriver.yaml
- controller-deployment.yaml
- controller-serviceaccount.yaml
```
