### ISSUE TITLE
Pod not supported on Fargate: fields not supported: HostNetwork, invalid SecurityContext fields: Privileged, port contains HostIP or HostPort

### ISSUE THREAD

**Issue by OneideLuizSchneider** [kubernetes-sigs/aws-efs-csi-driver#589]
/kind bug

I'm following this article: <https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html>
when I install the CSI Driver I'm getting this error:
`Pod not supported on Fargate: fields not supported: HostNetwork, invalid SecurityContext fields: Privileged, port contains HostIP or HostPort`
On this step:
```
helm upgrade -i aws-efs-csi-driver aws-efs-csi-driver/aws-efs-csi-driver \
    --namespace kube-system \
    --set image.repository=xxxxx.dkr.ecr.xxxxx.amazonaws.com/eks/aws-efs-csi-driver \
    --set controller.serviceAccount.create=false \
    --set controller.serviceAccount.name=efs-csi-controller-sa
```

**Anything else we need to know?**:
I'm using Fargate Profiles.

This article <https://stackoverflow.com/questions/69344438/efs-csi-driver-on-eks-fargate> says that `Pod that required hostNetwork: true cannot run on Fargate. You need to install the EFS driver on EC2 node group by using a namespace not in the Fargate profile.`

I'm not sure if it works on ***Fargate Profiles***.

**Environment**
- Kubernetes version 1.21
- Driver version: latest

**Comment by Shunpoco** [comment]
I had the same issue in my EKS cluster that uses both fargate nodes and EC2 nodes.

Because my fargate profile forces schedulers to use a fargate node when I deploy a pod on `kube-system`, I caught the exact same error as you.
So in my case, I created another namespace and deploy the service account and other resources from Helm on this new namespace, and finally it worked fine.

**Comment by prashant-shahi** [comment]
Any update on this issue?
