### ISSUE TITLE
Add Storage Class to static_provisioning and statefulset examples

### ISSUE THREAD

**Issue by pptb-aws** [kubernetes-sigs/aws-efs-csi-driver#639]
**Is your feature request related to a problem?/Why is this needed**

The static_provisioning and statefulset examples do not have a storageclass in the example.  This may result in confusion for people when looking at these examples when all others have storageclasses.

/feature

**Describe the solution you'd like in detail**

Add storageclass objects to the static_provisioning and statefulset examples

**Describe alternatives you've considered**

If there is a reason not to include these, please describe it in the readme.

**Additional context**

**Comment by cmartintlh** [comment]
I think I'm having difficulty with this as well. I created a static provisioned PV/PVC with an empty storageClassName. Since gp2 storage class in the EKS cluster was set as the default, this changed my PVC to use the gp2 storageClass, though it was still linked to my static provisioned PV using the EFS CSI driver. This did cause issues when trying to run `kubectl apply`, as it was attempting to revert the immutable storageClassName to an empty string.

Should we create a storage class for the static provisioning method? Would it just be something like:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-static
provisioner: efs.csi.aws.com
```
