### ISSUE TITLE
no matches for kind "CSIDriver" in version "storage.k8s.io/v1beta1"

### ISSUE THREAD

**Issue by khteh** [kubernetes-sigs/aws-efs-csi-driver#76]
/kind bug

**What happened?**
Applying the manifest from master on AWS EKS running on version `v1.13.7-eks-c57ff8` bumps into the error.

**What you expected to happen?**
Successfully applied the manifest without any error.

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
```
$ k version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T17:09:13Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.8-eks-a977ba", GitCommit:"a977bab148535ec195f12edc8720913c7b943f9c", GitTreeState:"clean", BuildDate:"2019-07-29T20:47:04Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Driver version: Not sure what you mean. Download the latest from this repo.

**Comment by leakingtapan** [comment]
That's because `CSIDriver` CRD move to be built-in since 1.14: https://kubernetes-csi.github.io/docs/csi-driver-object.html#changes-from-alpha-to-beta

This is also one of the reason that master branch only works with 1.14 as documented in the compatibility [matrix](https://github.com/kubernetes-sigs/aws-efs-csi-driver#kubernetes-version-compability-matrix)
